# Generated by Django 4.1.2 on 2022-10-18 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Teams",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=120)),
                (
                    "designation",
                    models.CharField(
                        blank=True, max_length=1000, verbose_name="Designation"
                    ),
                ),
                (
                    "profile_image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="Teams/",
                        verbose_name="Team Image",
                    ),
                ),
                (
                    "team_mail",
                    models.EmailField(max_length=254, verbose_name="Team Email"),
                ),
            ],
        ),
    ]
