# Generated by Django 3.2.6 on 2022-10-30 10:22

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_eventsfaq'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventPerks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(default='', max_length=100)),
                ('image', models.ImageField(blank=True, upload_to='event/perks/', verbose_name="Event's Perks image")),
                ('description', ckeditor_uploader.fields.RichTextUploadingField()),
            ],
            options={
                'verbose_name_plural': 'Event Perks',
            },
        ),
        migrations.CreateModel(
            name='EventRules',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rule', models.TextField(verbose_name='Event Rule')),
            ],
            options={
                'verbose_name_plural': 'Event Rules',
            },
        ),
        migrations.CreateModel(
            name='EventsPartners',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=100, verbose_name='Title')),
                ('image', models.ImageField(blank=True, upload_to='event/partners/', verbose_name='Event Partner')),
            ],
            options={
                'verbose_name_plural': 'Event Partners',
            },
        ),
    ]
