# Generated by Django 4.1.2 on 2022-10-18 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0002_rename_teams_team"),
    ]

    operations = [
        migrations.AddField(
            model_name="team",
            name="team_linkedin",
            field=models.CharField(
                blank=True, max_length=120, verbose_name="Team linkedin"
            ),
        ),
        migrations.AddField(
            model_name="team",
            name="team_phone",
            field=models.CharField(
                blank=True, max_length=15, verbose_name="Team pnumber"
            ),
        ),
        migrations.AddField(
            model_name="team",
            name="team_twitter",
            field=models.CharField(
                blank=True, max_length=120, verbose_name="Team twitter"
            ),
        ),
    ]
