# Generated by Django 4.1.2 on 2022-10-20 20:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0003_team_team_linkedin_team_team_phone_team_team_twitter"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Team",
        ),
    ]
