# Generated by Django 3.2.6 on 2022-11-01 21:28

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_eventrounds'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(db_index=True, max_length=100, unique=True, verbose_name='Event Name')),
                ('card_image', models.ImageField(blank=True, upload_to='event/main/card/', verbose_name="Event's Card image")),
                ('background_image', models.ImageField(blank=True, upload_to='event/main/background/', verbose_name="Event's background image")),
                ('tagline', models.CharField(max_length=255, verbose_name='Event Tagline')),
                ('description', ckeditor_uploader.fields.RichTextUploadingField(blank=True, verbose_name="Event's Description")),
                ('card_description', ckeditor_uploader.fields.RichTextUploadingField(blank=True, verbose_name="Event's Card Description")),
                ('google_form', models.URLField(blank=True, null=True, verbose_name="Event's Google Form")),
                ('event_priority', models.IntegerField(default=1, verbose_name='priority of event')),
                ('event_status', models.CharField(choices=[('U', 'Upcoming'), ('L', 'Live'), ('O', 'Over')], default='U', max_length=1, verbose_name='Event Status')),
                ('mobile_background_image', models.ImageField(blank=True, default=None, null=True, upload_to='event/main/background/', verbose_name="Event's Mobile background image")),
                ('logo_image', models.ImageField(blank=True, default=None, null=True, upload_to='event/main/logo/', verbose_name="Event's logo image")),
                ('event_faqs', models.ManyToManyField(blank=True, related_name='events_event_faqs_of', to='events.EventsFAQ')),
                ('events_coordinators', models.ManyToManyField(blank=True, to='events.EventCoordinator')),
            ],
            options={
                'verbose_name_plural': 'Events',
            },
        ),
    ]
