# Generated by Django 3.2.6 on 2022-11-02 19:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0007_auto_20221103_0032'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='seo',
            field=models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='events.eventseo'),
        ),
    ]
