# Generated by Django 4.1.2 on 2022-11-28 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0008_alter_event_seo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='event_faqs',
            field=models.ManyToManyField(blank=True, related_name='%(app_label)s_%(class)s_faqs_of', to='events.eventsfaq'),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_partners',
            field=models.ManyToManyField(related_name='%(app_label)s_%(class)s_partners_of', to='events.eventspartners', verbose_name='Partners/Sponsors Of Events'),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_perks',
            field=models.ManyToManyField(blank=True, related_name='%(app_label)s_%(class)s_perks_of', to='events.eventperks', verbose_name='Event Perks'),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_rounds',
            field=models.ManyToManyField(blank=True, related_name='%(app_label)s_%(class)s_rounds_of', to='events.eventrounds', verbose_name='Event Rounds'),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_rules',
            field=models.ManyToManyField(blank=True, related_name='%(app_label)s_%(class)s_rule_of', to='events.eventrules', verbose_name='Event Rules'),
        ),
    ]
