# Generated by Django 3.2.6 on 2022-12-12 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0016_alter_otp_date_expired'),
        ('events', '0011_alter_services_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventrounds',
            name='CAUser',
            field=models.ManyToManyField(blank=True, to='user.CAUser', verbose_name='CA User'),
        ),
    ]
