# Generated by Django 3.2.6 on 2022-12-23 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0012_eventrounds_causer'),
    ]

    operations = [
        migrations.AddField(
            model_name='services',
            name='img',
            field=models.ImageField(blank=True, upload_to='services/'),
        ),
    ]
