# Generated by Django 3.2.6 on 2022-12-26 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0014_auto_20221225_1909'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='Type',
            field=models.CharField(default='', max_length=100, verbose_name='Event Type'),
        ),
        migrations.AddField(
            model_name='event',
            name='registraion_end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='registraion_start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
