# Generated by Django 3.2.6 on 2022-12-26 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0015_auto_20221226_2148'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='event_eligibility',
            field=models.ManyToManyField(blank=True, related_name='events_event_elgiblty_of', to='events.EventRules', verbose_name='Elegiblity Rules'),
        ),
    ]
