# Generated by Django 3.2.6 on 2022-12-27 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0016_event_event_eligibility'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventcoordinator',
            name='image',
            field=models.ImageField(blank=True, upload_to='event/coordinator/', verbose_name='Event Coordinator'),
        ),
    ]
