# Generated by Django 3.2.6 on 2022-12-27 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0017_eventcoordinator_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='background_image',
            field=models.ImageField(blank=True, upload_to='background/', verbose_name="Event's background image"),
        ),
        migrations.AlterField(
            model_name='event',
            name='card_image',
            field=models.ImageField(blank=True, upload_to='card/', verbose_name="Event's Card image"),
        ),
    ]
