# Generated by Django 3.2.6 on 2023-01-01 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0020_alter_event_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='services',
            name='questions',
            field=models.TextField(default='{}', max_length=1000),
        ),
    ]
