# Generated by Django 3.2.6 on 2023-01-05 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0022_services_no_of_qa'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='services',
            name='questions',
        ),
        migrations.AddField(
            model_name='services',
            name='question1',
            field=models.TextField(default='', max_length=1000),
        ),
        migrations.AddField(
            model_name='services',
            name='question2',
            field=models.TextField(default='', max_length=1000),
        ),
    ]
