# Generated by Django 3.2.6 on 2023-01-09 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0023_auto_20230106_0438'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='created_at',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='eventperks',
            name='description',
            field=models.TextField(default='', max_length=100),
        ),
    ]
