# Generated by Django 3.2.6 on 2023-01-19 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0024_auto_20230109_1523'),
    ]

    operations = [
        migrations.AlterField(
            model_name='services',
            name='question1',
            field=models.TextField(blank=True, default='', max_length=1000),
        ),
        migrations.AlterField(
            model_name='services',
            name='question2',
            field=models.TextField(blank=True, default='', max_length=1000),
        ),
    ]
