version: "3"
services:
  redis:
    image: redis:7-alpine
    command: redis-server
    expose:
         - 6379

  esummit23-backend:
    build:
      context: ./
      dockerfile: Dockerfile
    working_dir: /usr/esummit23-backend
    environment:
            #            SECRET_KEY: ltx_c@+)ak_@6l8&r1g78&y*=-^#_(ts&=3^9rzibepdnrt&f3
            #SECRET_KEY: ltx_c@+)ak_@6l8&r1g78&y*=-^#_(ts&=3^9rzibepdnrt&f3

      - RAZORPAY_KEY_ID = rzp_live_U0W39W3I1yR00g
      - RAZORPAY_SECRET_KEY = RndrTeCVPTxYTJxVt10S7KET
      - REDIS_HOST=redis
      - ENVIRONMENT = production
      - AWS_ACCESS_KEY_ID = AKIAT4QCDQEC2VEPQUMK
      - AWS_SECRET_ACCESS_KEY = 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
      - AWS_STORAGE_BUCKET_NAME = e-cell-server-bucket
      - AWS_S3_CUSTOM_DOMAIN = .s3.amazonaws.com
      - EMAIL_HOST_USER = no.reply.esummit@gmail.com
      - EMAIL_HOST_PASSWORD = pnqlnairfeuhncmg
      - SECRET_KEY= ltx_c@+)ak_@5l8&r1g78&y*=-^#_(ts&=3^9rzibepdnrt&f3

    volumes:
            - ./:/usr/esummit23-backend
    expose:
      - 9000
    ports:
      - "9000:9000"
  worker:
        restart: always
        build:
                context: ./
                dockerfile : Dockerfile
        command: celery -A esummit worker -l info -P gevent
        working_dir: /usr/esummit23-backend
        volumes:
            - ./:/usr/esummit23-backend
#   esummit22-frontend:
#     build:
#       context: ./codebase/esummit23-frontend
#       dockerfile: Dockerfile
#     working_dir: /usr/esummit23-frontend

#     expose:
#       - 3000


#   nginx:
#     image: nginx:latest
#     restart: always
#     ports:
#       - 82:80
#     volumes:
#       - ./nginx/nginx-proxy.conf:/etc/nginx/conf.d/default.conf:ro
#       # - static-ui-content:/usr/E-cell-Website/frontend/build
#       - static-ui-content:/usr/esummit-frontend/build


#     command: nginx -g 'daemon off';
# volumes:
#   # static-ui-content:
#   static-ui-content: