# Generated by Django 3.2.6 on 2023-01-12 16:40

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('CAP', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Goodies',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('item', models.CharField(default='null', max_length=500, verbose_name='Item')),
                ('description', models.CharField(default='null', max_length=500)),
                ('price', models.IntegerField(default='null', verbose_name='Price')),
            ],
            options={
                'verbose_name_plural': 'Goodies',
            },
        ),
        migrations.CreateModel(
            name='Leaderboard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('esummitId', models.CharField(max_length=50)),
                ('taskassign', models.IntegerField(default=0, verbose_name='Task Assigned')),
                ('taskcomplete', models.IntegerField(default=0, verbose_name='Task Completed')),
                ('pointsearned', models.IntegerField(default=0, verbose_name='points')),
                ('discount', models.IntegerField(default=0, verbose_name='Discount(%)')),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Leaderboard',
            },
        ),
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('images', models.ImageField(default='null', upload_to='Submission/', verbose_name='Submitted Images')),
                ('esummitId', models.CharField(default='null', max_length=50)),
                ('check', models.BooleanField(default=False, verbose_name='Team Check')),
                ('verify', models.BooleanField(default=False, verbose_name='Team Accepted')),
                ('mlpoints', models.IntegerField(default='null', verbose_name='Points ML')),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Submission',
            },
        ),
        migrations.AlterModelOptions(
            name='task',
            options={'verbose_name_plural': 'Tasks'},
        ),
        migrations.AddField(
            model_name='task',
            name='created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='task',
            name='desc',
            field=models.CharField(default='null', max_length=1000, verbose_name='description'),
        ),
        migrations.AddField(
            model_name='task',
            name='format',
            field=models.CharField(default='null', max_length=50, verbose_name='Submission Format'),
        ),
        migrations.AddField(
            model_name='task',
            name='keywords',
            field=models.CharField(default='null', max_length=400),
        ),
        migrations.AddField(
            model_name='task',
            name='points',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='task',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='task',
            name='url',
            field=models.CharField(default='null', max_length=200),
        ),
    ]
