# Generated by Django 3.2.6 on 2023-01-14 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CAP', '0003_alter_task_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='submission',
            name='mlpoints',
        ),
        migrations.AddField(
            model_name='submission',
            name='taskId',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='task',
            name='task_id',
            field=models.IntegerField(default=0),
        ),
    ]
