# Generated by Django 3.2.6 on 2023-01-14 21:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CAP', '0004_auto_20230115_0223'),
        ('CAP', '0005_alter_task_task_id'),
    ]

    operations = [
    ]
