# Generated by Django 3.2.6 on 2023-01-15 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CAP', '0006_merge_0004_auto_20230115_0223_0005_alter_task_task_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='name',
        ),
        migrations.AddField(
            model_name='submission',
            name='point',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='submission',
            name='esummitId',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='submission',
            name='images',
            field=models.ImageField(upload_to='Submission/', verbose_name='Submitted Images'),
        ),
    ]
