# Generated by Django 3.2.6 on 2023-01-15 17:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CAP', '0007_auto_20230115_1848'),
    ]

    operations = [
        migrations.RenameField(
            model_name='submission',
            old_name='point',
            new_name='points',
        ),
    ]
