# Generated by Django 3.2.6 on 2023-12-05 14:56

import django.core.validators
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('CAP', '0008_rename_point_submission_points'),
    ]

    operations = [
        migrations.CreateModel(
            name='CapUsers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(default='', max_length=50, verbose_name='Name')),
                ('email', models.EmailField(db_index=True, default='', max_length=100, unique=True, verbose_name='Email')),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], default='', max_length=10, verbose_name='gender')),
                ('phone_number', models.CharField(blank=True, max_length=10, null=True, validators=[django.core.validators.RegexValidator(message='Phone Number Not Valid', regex='^[6-9]\\d{9}$')], verbose_name='Phone Number')),
                ('college', models.CharField(default='', max_length=100, verbose_name='College')),
                ('state', models.CharField(default='', max_length=100, verbose_name='State')),
                ('city', models.CharField(default='', max_length=100, verbose_name='City')),
                ('studyYear', models.CharField(default='', max_length=10, verbose_name='YearofStudy')),
                ('esummitId', models.CharField(default='', max_length=100, verbose_name='EsummitId')),
                ('refferedby', models.CharField(default='', max_length=100, verbose_name='RefferedBy')),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('password', models.CharField(default='nopassward<django.db.models.fields.CharField>', max_length=100, verbose_name='password')),
                ('authToken', models.CharField(blank=True, default='', max_length=1000, null=True)),
            ],
            options={
                'verbose_name_plural': 'Capusers',
            },
        ),
    ]
