# Generated by Django 3.2.6 on 2023-12-16 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CAP', '0010_auto_20231216_0123'),
    ]

    operations = [
        migrations.AddField(
            model_name='capusers',
            name='taskCompleted',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='capusers',
            name='totalpoints',
            field=models.IntegerField(default=0),
        ),
    ]
