# Generated by Django 3.2.6 on 2023-12-16 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CAP', '0011_auto_20231216_0948'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskstatus',
            name='status',
            field=models.CharField(choices=[('LIVE', 'Live'), ('PEND', 'Pending'), ('VERI', 'Verifed'), ('EXPI', 'Expired')], default='LIVE', max_length=200),
        ),
    ]
