# Generated by Django 3.2.6 on 2023-12-16 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CAP', '0012_alter_taskstatus_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='taskstatus',
            name='status',
        ),
        migrations.RemoveField(
            model_name='taskstatus',
            name='task',
        ),
        migrations.AddField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('LIVE', 'Live'), ('PEND', 'Pending'), ('VERI', 'Verifed'), ('EXPI', 'Expired')], default='null', max_length=200),
        ),
        migrations.AddField(
            model_name='taskstatus',
            name='taskId',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='task',
            name='deadline',
            field=models.DateTimeField(default='null'),
        ),
        migrations.AlterField(
            model_name='taskstatus',
            name='taskpoint',
            field=models.CharField(default='', max_length=20),
        ),
    ]
