# Generated by Django 3.2.6 on 2023-12-21 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CAP', '0014_alter_task_deadline'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('LIVE', 'Live'), ('PEND', 'Pending'), ('VERI', 'Verifed'), ('EXPI', 'Expired')], default='LIVE', max_length=200),
        ),
        migrations.AlterField(
            model_name='taskstatus',
            name='images',
            field=models.ImageField(null=True, upload_to='Submission/', verbose_name='Submitted Images'),
        ),
        migrations.AlterField(
            model_name='taskstatus',
            name='taskId',
            field=models.CharField(default='', max_length=100, verbose_name='Esummitid'),
        ),
        migrations.AlterField(
            model_name='taskstatus',
            name='taskpoint',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
