# Generated by Django 3.2.6 on 2023-12-22 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CAP', '0017_auto_20231222_0958'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskstatus',
            name='status',
            field=models.CharField(choices=[('LIVE', 'Live'), ('PEND', 'Pending'), ('VERI', 'Verifed'), ('EXPI', 'Expired'), ('NOTACC', 'Not accepted')], default='null', max_length=200),
        ),
    ]
