# Generated by Django 3.2.6 on 2023-12-22 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CAP', '0018_alter_taskstatus_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='taskstatus',
            options={'verbose_name_plural': 'Taskstats'},
        ),
        migrations.AlterField(
            model_name='taskstatus',
            name='taskId',
            field=models.CharField(default='', max_length=100, verbose_name='TaskId'),
        ),
    ]
