# Generated by Django 3.2.6 on 2023-12-22 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CAP', '0019_auto_20231222_1046'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskstatus',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Verified', 'Verifed'), ('Expired', 'Expired'), ('Not Accepted', 'Not accepted')], default='null', max_length=200),
        ),
    ]
