# Generated by Django 3.2.6 on 2023-12-22 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CAP', '0020_alter_taskstatus_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='capusers',
            name='taskAssigned',
            field=models.CharField(default='', max_length=100, verbose_name='assigned Tasks'),
        ),
        migrations.AlterField(
            model_name='taskstatus',
            name='status',
            field=models.CharField(choices=[('None', ''), ('Pending', 'Pending'), ('Verified', 'Verifed'), ('Expired', 'Expired'), ('Not Accepted', 'Not accepted')], default='None', max_length=200),
        ),
    ]
