# Generated by Django 3.2.6 on 2023-12-22 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CAP', '0021_auto_20231222_2154'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskstatus',
            name='status',
            field=models.CharField(choices=[('None', ''), ('Pending', 'Pending'), ('Verified', 'Verifed'), ('Expired', 'Expired'), ('Not Accepted', 'Not accepted')], default='Pending', max_length=200),
        ),
    ]
