# Generated by Django 3.2.6 on 2023-12-22 23:49

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CAP', '0023_alter_taskstatus_images'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskstatus',
            name='images',
            field=models.FileField(null=True, upload_to='Submission/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'pdf', 'xls', 'xlsx'])], verbose_name='Submitted Images'),
        ),
    ]
