# Generated by Django 3.2.6 on 2023-12-23 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CAP', '0024_alter_taskstatus_images'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskstatus',
            name='images',
            field=models.FileField(null=True, upload_to='Submission/', verbose_name='Submitted Images'),
        ),
    ]
