# Generated by Django 3.2.6 on 2024-02-01 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CAP', '0025_alter_taskstatus_images'),
    ]

    operations = [
        migrations.AddField(
            model_name='capusers',
            name='ticketssold',
            field=models.IntegerField(default=0),
        ),
    ]
