# Generated by Django 3.2.6 on 2024-10-19 07:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CAP', '0025_alter_taskstatus_images'),
    ]

    operations = [
        migrations.AddField(
            model_name='capusers',
            name='referral_code',
            field=models.CharField(blank=True, max_length=8, unique=True, verbose_name='ReferralCode'),
        ),
        migrations.AddField(
            model_name='capusers',
            name='ticketssold',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='Referral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('referral_code', models.CharField(max_length=50, unique=True)),
                ('link_clicks', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('referrer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CAP.capusers')),
            ],
        ),
    ]
