# Generated by Django 3.2.6 on 2024-10-19 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CAP', '0026_auto_20241019_1253'),
    ]

    operations = [
        migrations.AlterField(
            model_name='capusers',
            name='referral_code',
            field=models.CharField(blank=True, max_length=50, unique=True, verbose_name='ReferralCode'),
        ),
    ]
