# Generated by Django 3.2.6 on 2024-10-19 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CAP', '0027_alter_capusers_referral_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='capusers',
            name='referral_code',
            field=models.CharField(default='', max_length=50, verbose_name='ReferralCode'),
        ),
    ]
