# Generated by Django 3.2.6 on 2024-10-19 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CAP', '0029_alter_referral_referral_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='capusers',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], default='', max_length=10, verbose_name='Gender'),
        ),
        migrations.AlterField(
            model_name='capusers',
            name='password',
            field=models.CharField(default='nopassword', max_length=100, verbose_name='Password'),
        ),
        migrations.AlterField(
            model_name='capusers',
            name='referral_code',
            field=models.CharField(blank=True, max_length=10, null=True, unique=True, verbose_name='Referral Code'),
        ),
        migrations.AlterField(
            model_name='capusers',
            name='refferedby',
            field=models.CharField(default='', max_length=100, verbose_name='Referred By'),
        ),
        migrations.AlterField(
            model_name='capusers',
            name='studyYear',
            field=models.CharField(default='', max_length=10, verbose_name='Year of Study'),
        ),
        migrations.AlterField(
            model_name='capusers',
            name='taskAssigned',
            field=models.CharField(default='', max_length=100, verbose_name='Assigned Tasks'),
        ),
    ]
