# Generated by Django 3.2.6 on 2022-10-22 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='speakers',
            name='profile_image',
            field=models.ImageField(upload_to='speakers/', verbose_name='Speaker Image'),
        ),
    ]
