# Generated by Django 3.2.6 on 2023-01-13 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0002_alter_speakers_profile_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='speakers',
            name='date_event',
        ),
        migrations.RemoveField(
            model_name='speakers',
            name='time_event',
        ),
        migrations.AddField(
            model_name='speakers',
            name='event_year',
            field=models.CharField(default='2023', max_length=4, verbose_name='Event Year'),
        ),
    ]
