# Generated by Django 3.2.6 on 2022-10-10 11:13

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0002_auto_20221009_1906'),
    ]

    operations = [
        migrations.AddField(
            model_name='speakers',
            name='created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='speakers',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
