# Generated by Django 3.2.6 on 2022-10-20 20:42

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0003_auto_20221010_1643'),
    ]

    operations = [
        migrations.CreateModel(
            name='Colors',
            fields=[
                ('colourCategory', models.CharField(max_length=100)),
                ('colourid', models.AutoField(primary_key=True, serialize=False)),
                ('colourName', models.CharField(max_length=100)),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
