# Generated by Django 4.1.2 on 2022-10-20 18:49

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("public", "0003_auto_20221010_1643"),
    ]

    operations = [
        migrations.CreateModel(
            name="Team",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=120)),
                (
                    "designation",
                    models.CharField(
                        blank=True, max_length=1000, verbose_name="Designation"
                    ),
                ),
                (
                    "profile_image",
                    models.ImageField(upload_to="Teams/", verbose_name="Team Image"),
                ),
                (
                    "team_mail",
                    models.EmailField(max_length=254, verbose_name="Team Email"),
                ),
                (
                    "team_phone",
                    models.CharField(
                        blank=True, max_length=15, verbose_name="Team pnumber"
                    ),
                ),
                (
                    "team_twitter",
                    models.CharField(
                        blank=True, max_length=120, verbose_name="Team twitter"
                    ),
                ),
                (
                    "team_linkedin",
                    models.CharField(
                        blank=True, max_length=120, verbose_name="Team linkedin"
                    ),
                ),
                ("created", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
