# Generated by Django 3.2.6 on 2023-01-14 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0003_auto_20230114_0133'),
    ]

    operations = [
        migrations.AddField(
            model_name='speakers',
            name='priority',
            field=models.IntegerField(default=0),
        ),
    ]
