# Generated by Django 4.1.2 on 2022-10-20 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("public", "0004_team"),
    ]

    operations = [
        migrations.AlterField(
            model_name="team",
            name="profile_image",
            field=models.ImageField(upload_to="teams/", verbose_name="Team Image"),
        ),
    ]
