# Generated by Django 3.2.6 on 2023-02-11 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0004_speakers_priority'),
    ]

    operations = [
        migrations.AddField(
            model_name='speakers',
            name='description',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='speakers',
            name='venue',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='speakers',
            name='event_year',
            field=models.CharField(default='2023', max_length=30, verbose_name='Event Year'),
        ),
    ]
