# Generated by Django 3.2.6 on 2023-02-12 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0005_auto_20230211_2354'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='team_fb',
            field=models.CharField(blank=True, max_length=120, verbose_name='Team linkedin'),
        ),
        migrations.AddField(
            model_name='team',
            name='team_insta',
            field=models.CharField(blank=True, max_length=120, verbose_name='Team linkedin'),
        ),
    ]
