# Generated by Django 3.2.6 on 2023-02-12 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0006_auto_20230212_2224'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='team_fb',
            field=models.CharField(blank=True, max_length=120, verbose_name='Team Facebook'),
        ),
        migrations.AlterField(
            model_name='team',
            name='team_insta',
            field=models.CharField(blank=True, max_length=120, verbose_name='Team Instagram'),
        ),
        migrations.AlterField(
            model_name='team',
            name='team_phone',
            field=models.CharField(blank=True, max_length=15, verbose_name='Team phone number'),
        ),
    ]
