# Generated by Django 3.2.6 on 2023-02-14 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0007_auto_20230212_2225'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='priority',
            field=models.IntegerField(default=0),
        ),
    ]
