# Generated by Django 3.2.6 on 2022-10-22 08:45

import django.core.validators
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('events', '__first__'),
        ('CAP', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StartupUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=50, verbose_name='Name')),
                ('email', models.EmailField(db_index=True, max_length=100, verbose_name='EMail Id')),
                ('phone_number', models.CharField(blank=True, max_length=10, null=True, validators=[django.core.validators.RegexValidator(message='Phone Number Not Valid', regex='^[6-9]\\d{9}$')], verbose_name='Phone Number')),
                ('payment', models.IntegerField(default=0)),
                ('referred_by', models.CharField(max_length=20)),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('password', models.CharField(max_length=16)),
                ('startup_name', models.CharField(max_length=50, verbose_name='Startup Name')),
                ('domain', models.CharField(max_length=50, verbose_name='Domain')),
                ('category', models.CharField(max_length=50, verbose_name='Category')),
                ('description', models.CharField(max_length=200, verbose_name='Description')),
                ('esummit_id', models.CharField(db_index=True, max_length=20, unique=True)),
                ('services', models.ManyToManyField(to='events.Services', verbose_name='Services')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CAUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=50, verbose_name='Name')),
                ('email', models.EmailField(db_index=True, max_length=100, verbose_name='EMail Id')),
                ('phone_number', models.CharField(blank=True, max_length=10, null=True, validators=[django.core.validators.RegexValidator(message='Phone Number Not Valid', regex='^[6-9]\\d{9}$')], verbose_name='Phone Number')),
                ('payment', models.IntegerField(default=0)),
                ('referred_by', models.CharField(max_length=20)),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('password', models.CharField(max_length=16)),
                ('collage', models.CharField(max_length=50, verbose_name='Collage')),
                ('points', models.IntegerField(default=0)),
                ('branch', models.CharField(max_length=50, verbose_name='Branch')),
                ('year', models.CharField(max_length=10, verbose_name='Year')),
                ('city', models.CharField(max_length=50, verbose_name='City')),
                ('state', models.CharField(max_length=50, verbose_name='State')),
                ('esummit_id', models.CharField(db_index=True, max_length=20, unique=True)),
                ('taskAssigned', models.ManyToManyField(related_name='task_assigned', to='CAP.Task', verbose_name='Task Assigned')),
                ('taskCompleted', models.ManyToManyField(related_name='task_cmpleted', to='CAP.Task', verbose_name='Task Completed')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
