# Generated by Django 3.2.6 on 2022-11-07 13:40

import django.core.validators
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_auto_20221102_0258'),
    ]

    operations = [
        migrations.CreateModel(
            name='Querry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
                ('email', models.EmailField(db_index=True, max_length=100, verbose_name='EMail Id')),
                ('phone_number', models.CharField(blank=True, max_length=10, null=True, validators=[django.core.validators.RegexValidator(message='Phone Number Not Valid', regex='^[6-9]\\d{9}$')], verbose_name='Phone Number')),
                ('message', models.TextField(max_length=1000, verbose_name='Message')),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
