# Generated by Django 3.2.6 on 2022-11-07 18:36

import datetime
from django.db import migrations, models
import django.utils.timezone
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_auto_20221102_0258'),
    ]

    operations = [
        migrations.CreateModel(
            name='OTP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Email', models.EmailField(max_length=254)),
                ('Esummit_Id', models.CharField(max_length=15)),
                ('Otp', models.CharField(max_length=15)),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now)),
                ('date_expired', models.DateTimeField(default=datetime.datetime(2022, 11, 7, 19, 6, 5, 687483, tzinfo=utc))),
            ],
        ),
    ]
