# Generated by Django 3.2.6 on 2022-11-07 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_querry'),
    ]

    operations = [
        migrations.AddField(
            model_name='querry',
            name='resolved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='querry',
            name='resolved_by',
            field=models.TextField(blank=True, null=True),
        ),
    ]
