# Generated by Django 3.2.6 on 2022-11-08 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_auto_20221107_1915'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='querry',
            options={'verbose_name_plural': 'Queries'},
        ),
        migrations.AlterField(
            model_name='causer',
            name='password',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='proffuser',
            name='password',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='startupuser',
            name='password',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='studentuser',
            name='password',
            field=models.CharField(max_length=100),
        ),
    ]
