# Generated by Django 3.2.6 on 2022-11-11 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_alter_causer_referred_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='causer',
            name='email',
            field=models.EmailField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='causer',
            name='password',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='causer',
            name='referred_by',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='proffuser',
            name='email',
            field=models.EmailField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='proffuser',
            name='password',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='startupuser',
            name='email',
            field=models.EmailField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='startupuser',
            name='password',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='studentuser',
            name='email',
            field=models.EmailField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='studentuser',
            name='password',
            field=models.TextField(blank=True),
        ),
    ]
