# Generated by Django 3.2.6 on 2022-11-11 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0010_auto_20221111_1634'),
    ]

    operations = [
        migrations.AlterField(
            model_name='causer',
            name='password',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='proffuser',
            name='password',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='startupuser',
            name='password',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='studentuser',
            name='password',
            field=models.TextField(),
        ),
    ]
