# Generated by Django 3.2.6 on 2022-11-11 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0011_auto_20221111_1648'),
    ]

    operations = [
        migrations.AlterField(
            model_name='causer',
            name='email',
            field=models.EmailField(db_index=True, max_length=100, unique=True, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='proffuser',
            name='email',
            field=models.EmailField(db_index=True, max_length=100, unique=True, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='startupuser',
            name='email',
            field=models.EmailField(db_index=True, max_length=100, unique=True, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='studentuser',
            name='email',
            field=models.EmailField(db_index=True, max_length=100, unique=True, verbose_name='Email'),
        ),
    ]
