# Generated by Django 3.2.6 on 2022-12-06 10:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_otp'),
        ('user', '0012_auto_20221111_1649'),
    ]

    operations = [
    ]
