# Generated by Django 3.2.6 on 2022-12-10 05:54

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0013_merge_0006_otp_0012_auto_20221111_1649'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otp',
            name='date_expired',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 10, 6, 24, 15, 325968, tzinfo=utc)),
        ),
    ]
