# Generated by Django 3.2.6 on 2022-12-12 02:41

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0015_auto_20221210_1740'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otp',
            name='date_expired',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 12, 3, 11, 32, 397893, tzinfo=utc)),
        ),
    ]
