# Generated by Django 3.2.6 on 2022-12-15 16:22

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0016_alter_otp_date_expired'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='causer',
            name='branch',
        ),
        migrations.RemoveField(
            model_name='causer',
            name='collage',
        ),
        migrations.RemoveField(
            model_name='studentuser',
            name='college_name',
        ),
        migrations.AddField(
            model_name='causer',
            name='college',
            field=models.CharField(default='IIT Roorkee', max_length=50, verbose_name='College'),
        ),
        migrations.AlterField(
            model_name='otp',
            name='date_expired',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 15, 16, 52, 47, 348470, tzinfo=utc)),
        ),
    ]
