# Generated by Django 3.2.6 on 2022-12-21 16:57

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0018_auto_20221220_1503'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='causer',
            name='college',
        ),
        migrations.RemoveField(
            model_name='studentuser',
            name='college',
        ),
        migrations.RemoveField(
            model_name='teams',
            name='question',
        ),
        migrations.AddField(
            model_name='causer',
            name='collage',
            field=models.CharField(default='IIT Roorkee', max_length=50, verbose_name='Collage'),
        ),
        migrations.AddField(
            model_name='person',
            name='leader_status',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='studentuser',
            name='collage',
            field=models.CharField(default='IIT Roorkee', max_length=200, verbose_name='Collage Name'),
        ),
        migrations.AlterField(
            model_name='otp',
            name='date_expired',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 21, 17, 27, 55, 652571, tzinfo=utc)),
        ),
        migrations.RemoveField(
            model_name='teams',
            name='event',
        ),
        migrations.AddField(
            model_name='teams',
            name='event',
            field=models.CharField(max_length=50, null=True, verbose_name='Event'),
        ),
    ]
