# Generated by Django 3.2.6 on 2022-12-21 20:49

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0019_auto_20221221_2227'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otp',
            name='date_expired',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 21, 21, 19, 3, 715256, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='teams',
            name='leader',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='leader', to='user.person', verbose_name='Leader'),
        ),
    ]
