# Generated by Django 3.2.6 on 2022-12-23 11:19

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0020_auto_20221222_0219'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otp',
            name='date_expired',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 23, 11, 49, 52, 749644, tzinfo=utc)),
        ),
    ]
