# Generated by Django 3.2.6 on 2022-12-27 12:33

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0027_alter_otp_date_expired'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otp',
            name='date_expired',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 27, 13, 3, 41, 418064, tzinfo=utc)),
        ),
    ]
