# Generated by Django 3.2.6 on 2023-01-03 16:40

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0029_alter_otp_date_expired'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otp',
            name='date_expired',
            field=models.DateTimeField(default=datetime.datetime(2023, 1, 3, 17, 10, 27, 520664, tzinfo=utc)),
        ),
    ]
