# Generated by Django 3.2.6 on 2023-01-03 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0030_auto_20230101_0925'),
    ]

    operations = [
        migrations.AddField(
            model_name='causer',
            name='test',
            field=models.CharField(default='Test', max_length=50, verbose_name='Test'),
        ),
    ]
