# Generated by Django 3.2.6 on 2023-01-06 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0031_causer_test'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teams',
            name='submission_link',
            field=models.URLField(default='', null=True),
        ),
    ]
