# Generated by Django 3.2.6 on 2023-01-09 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0032_alter_teams_submission_link'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='causer',
            name='test',
        ),
        migrations.AddField(
            model_name='causer',
            name='gender',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Gender'),
        ),
        migrations.AlterField(
            model_name='proffuser',
            name='gender',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Gender'),
        ),
        migrations.AlterField(
            model_name='studentuser',
            name='gender',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Gender'),
        ),
    ]
