# Generated by Django 3.2.6 on 2023-01-09 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0033_auto_20230109_1819'),
    ]

    operations = [
        migrations.AlterField(
            model_name='causer',
            name='city',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='City'),
        ),
        migrations.AlterField(
            model_name='causer',
            name='state',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='State'),
        ),
        migrations.AlterField(
            model_name='causer',
            name='year',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Year'),
        ),
    ]
