# Generated by Django 3.2.6 on 2023-01-12 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0034_auto_20230109_2004'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='otp',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
    ]
