# Generated by Django 3.2.6 on 2023-01-14 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CAP', '0003_alter_task_name'),
        ('user', '0035_person_otp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='causer',
            name='taskCompleted',
            field=models.ManyToManyField(blank=True, related_name='task_completed', to='CAP.Task', verbose_name='Task Completed'),
        ),
    ]
