# Generated by Django 3.2.6 on 2023-01-18 05:16

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0036_alter_causer_taskcompleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='teams',
            name='submission_text2',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, default=''),
        ),
    ]
