# Generated by Django 3.2.6 on 2023-01-20 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0036_alter_causer_taskcompleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='causer',
            name='rank',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='causer',
            name='collage',
            field=models.CharField(default='IIT Roorkee', max_length=50, verbose_name='College'),
        ),
    ]
