# Generated by Django 3.2.6 on 2023-01-19 09:12

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0038_alter_teams_submission_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teams',
            name='submission_text',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='teams',
            name='submission_text2',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, default='', null=True),
        ),
    ]
