# Generated by Django 3.2.6 on 2023-01-20 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0038_alter_teams_submission_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='verified',
            field=models.BooleanField(default=True),
        ),
    ]
