# Generated by Django 3.2.6 on 2023-01-22 04:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0037_auto_20230120_2235'),
        ('user', '0039_auto_20230119_1442'),
        ('user', '0039_person_verified'),
    ]

    operations = [
    ]
