# Generated by Django 3.2.6 on 2023-01-23 16:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0040_merge_20230122_0936'),
        ('user', '0040_merge_20230123_2029'),
    ]

    operations = [
    ]
