# Generated by Django 3.2.6 on 2023-01-30 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0042_blockmail_blocknumber'),
    ]

    operations = [
        migrations.AlterField(
            model_name='causer',
            name='esummit_id',
            field=models.CharField(db_index=True, max_length=40, unique=True),
        ),
        migrations.AlterField(
            model_name='proffuser',
            name='esummit_id',
            field=models.CharField(db_index=True, max_length=40, unique=True),
        ),
        migrations.AlterField(
            model_name='proffuser',
            name='referred_by',
            field=models.CharField(blank=True, default='', max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='startupuser',
            name='esummit_id',
            field=models.CharField(db_index=True, max_length=40, unique=True),
        ),
        migrations.AlterField(
            model_name='startupuser',
            name='referred_by',
            field=models.CharField(blank=True, default='', max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='studentuser',
            name='esummit_id',
            field=models.CharField(db_index=True, max_length=40, unique=True),
        ),
        migrations.AlterField(
            model_name='studentuser',
            name='referred_by',
            field=models.CharField(blank=True, default='', max_length=40, null=True),
        ),
    ]
