# Generated by Django 3.2.6 on 2023-01-25 20:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0042_blockmail_blocknumber'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blocknumber',
            name='created',
        ),
        migrations.RemoveField(
            model_name='blocknumber',
            name='updated',
        ),
    ]
