# Generated by Django 3.2.6 on 2023-01-26 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0043_auto_20230126_0149'),
    ]

    operations = [
        migrations.AddField(
            model_name='blockmail',
            name='user',
            field=models.CharField(default=0, max_length=100),
        ),
    ]
