# Generated by Django 3.2.6 on 2023-02-15 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0043_auto_20230130_1326'),
    ]

    operations = [
        migrations.CreateModel(
            name='Teamecell',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Email', models.EmailField(max_length=254)),
                ('Otp', models.CharField(blank=True, max_length=15, null=True)),
                ('Name', models.CharField(max_length=30)),
            ],
            options={
                'verbose_name_plural': 'Teamecell',
            },
        ),
    ]
