# Generated by Django 3.2.6 on 2024-01-04 19:53

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0025_auto_20230119_1441'),
        ('user', '0044_teamecell'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(blank=True, max_length=10, null=True, verbose_name='Gender')),
                ('fullName', models.CharField(max_length=50, verbose_name='Full Name')),
                ('email', models.EmailField(db_index=True, max_length=100, unique=True, verbose_name='Email')),
                ('phone_number', models.CharField(blank=True, max_length=10, null=True, validators=[django.core.validators.RegexValidator(message='Phone Number Not Valid', regex='^[6-9]\\d{9}$')], verbose_name='Phone Number')),
                ('payment', models.IntegerField(default=0)),
                ('created', models.DateTimeField()),
                ('updated', models.DateTimeField(auto_now=True)),
                ('password', models.TextField()),
                ('authToken', models.CharField(blank=True, max_length=1000, null=True)),
                ('student_type', models.CharField(choices=[('IITR', 'IITR Student'), ('NONIITR', 'Non IITR Student')], default='NONIITR', max_length=10)),
                ('enrollment_no', models.CharField(blank=True, max_length=10, null=True, verbose_name='Enrollment Number(If IITR Student)')),
                ('city', models.CharField(blank=True, max_length=50, null=True)),
                ('state', models.CharField(blank=True, max_length=50, null=True)),
                ('country', models.CharField(default='India', max_length=200, verbose_name='Country')),
                ('pincode', models.CharField(default='', max_length=200, verbose_name='Pin Code')),
                ('State', models.CharField(default='', max_length=200, verbose_name='State')),
                ('college', models.CharField(default='IIT Roorkee', max_length=200, verbose_name='Collage Name')),
                ('esummit_id', models.CharField(db_index=True, max_length=40, unique=True)),
                ('referred_by', models.CharField(blank=True, default='', max_length=40, null=True)),
                ('Services', models.ManyToManyField(blank=True, to='events.Services')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Startup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(blank=True, max_length=10, null=True, verbose_name='Gender')),
                ('fullName', models.CharField(max_length=50, verbose_name='Full Name')),
                ('email', models.EmailField(db_index=True, max_length=100, unique=True, verbose_name='Email')),
                ('phone_number', models.CharField(blank=True, max_length=10, null=True, validators=[django.core.validators.RegexValidator(message='Phone Number Not Valid', regex='^[6-9]\\d{9}$')], verbose_name='Phone Number')),
                ('payment', models.IntegerField(default=0)),
                ('created', models.DateTimeField()),
                ('updated', models.DateTimeField(auto_now=True)),
                ('password', models.TextField()),
                ('authToken', models.CharField(blank=True, max_length=1000, null=True)),
                ('startup_name', models.CharField(max_length=50, verbose_name='Startup Name')),
                ('domain', models.CharField(max_length=50, verbose_name='Domain')),
                ('esummit_id', models.CharField(db_index=True, max_length=40, unique=True)),
                ('referred_by', models.CharField(blank=True, default='', max_length=40, null=True)),
                ('Services', models.ManyToManyField(blank=True, to='events.Services')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Proff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(blank=True, max_length=10, null=True, verbose_name='Gender')),
                ('fullName', models.CharField(max_length=50, verbose_name='Full Name')),
                ('email', models.EmailField(db_index=True, max_length=100, unique=True, verbose_name='Email')),
                ('phone_number', models.CharField(blank=True, max_length=10, null=True, validators=[django.core.validators.RegexValidator(message='Phone Number Not Valid', regex='^[6-9]\\d{9}$')], verbose_name='Phone Number')),
                ('payment', models.IntegerField(default=0)),
                ('created', models.DateTimeField()),
                ('updated', models.DateTimeField(auto_now=True)),
                ('password', models.TextField()),
                ('authToken', models.CharField(blank=True, max_length=1000, null=True)),
                ('organisation_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Organisation From')),
                ('position', models.CharField(blank=True, max_length=100, null=True, verbose_name='position')),
                ('esummit_id', models.CharField(db_index=True, max_length=40, unique=True)),
                ('referred_by', models.CharField(blank=True, default='', max_length=40, null=True)),
                ('Services', models.ManyToManyField(blank=True, to='events.Services')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
