# Generated by Django 3.2.6 on 2023-01-26 10:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0044_blockmail_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blockmail',
            name='user',
        ),
    ]
