# Generated by Django 3.2.6 on 2023-02-14 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0044_teamecell'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teamecell',
            name='Otp',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
