# Generated by Django 3.2.6 on 2023-01-26 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0045_remove_blockmail_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='blocknumber',
            name='user',
            field=models.CharField(default='', max_length=100),
        ),
    ]
