# Generated by Django 3.2.6 on 2024-01-09 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0045_auto_20240106_1522'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentuser',
            name='enrollment_no',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Enrollment Number(If IITR Student)'),
        ),
        migrations.AddField(
            model_name='studentuser',
            name='year',
            field=models.CharField(default='1', max_length=20, verbose_name='Year of study'),
        ),
    ]
