# Generated by Django 3.2.6 on 2024-01-05 05:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0045_proff_startup_student'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='startup',
            name='Services',
        ),
        migrations.RemoveField(
            model_name='student',
            name='Services',
        ),
        migrations.DeleteModel(
            name='Proff',
        ),
        migrations.DeleteModel(
            name='Startup',
        ),
        migrations.DeleteModel(
            name='Student',
        ),
    ]
