# Generated by Django 3.2.6 on 2024-01-28 12:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0046_auto_20240109_2332'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='startup',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='user.startupuser'),
        ),
    ]
