# Generated by Django 3.2.6 on 2023-01-26 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0047_blockmail_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blockmail',
            name='blockmail',
            field=models.CharField(db_index=True, max_length=100, unique=True, verbose_name='Email'),
        ),
    ]
