# Generated by Django 3.2.6 on 2023-01-25 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0002_alter_ticket_plan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='plan',
            field=models.CharField(default='', max_length=100, verbose_name='Plan'),
        ),
    ]
