# Generated by Django 3.2.6 on 2023-02-05 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0003_alter_ticket_plan'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReffealCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner', models.CharField(max_length=50, verbose_name='Owner')),
                ('code', models.CharField(blank=True, max_length=50, null=True, verbose_name='Code')),
                ('usage', models.IntegerField(default=0, verbose_name='Usage')),
            ],
        ),
    ]
