# Generated by Django 3.2.6 on 2023-02-11 11:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0004_reffealcode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='payment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ticket.payment', verbose_name='Payment'),
        ),
    ]
