# Generated by Django 3.2.6 on 2023-02-14 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0006_alter_ticket_quantity'),
    ]

    operations = [
        migrations.CreateModel(
            name='StatisticsParticipants',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Type', models.CharField(max_length=30)),
                ('Name', models.CharField(max_length=60)),
                ('SummitId', models.CharField(max_length=50)),
                ('PhoneNo', models.IntegerField(default=0)),
                ('Email', models.EmailField(max_length=50)),
                ('EventName', models.CharField(max_length=50)),
                ('TimeEntryExit', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'StatisticsParticipant',
            },
        ),
    ]
