# Generated by Django 3.2.6 on 2024-01-28 12:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0047_person_startup'),
        ('ticket', '0008_auto_20230216_0007'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='Person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ticket', to='user.person', verbose_name='Person'),
        ),
    ]
